# Generated by Django 4.1 on 2022-08-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('owned_by', models.CharField(max_length=36)),
                ('enabled_at', models.DateTimeField()),
                ('balance', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='wallet_api.customer')),
            ],
        ),
    ]
