# Generated by Django 4.1 on 2022-08-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api', '0002_customer_created_at_customer_token_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='token',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_api.customer'),
        ),
    ]
