# Generated by Django 4.1 on 2022-08-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api', '0004_rename_id_customer_xid_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_api.customer'),
        ),
    ]
