# Generated by Django 4.1 on 2022-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api', '0005_remove_wallet_customer_alter_wallet_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.CharField(default='disabled', max_length=25),
        ),
    ]
