# Generated by Django 4.1 on 2022-08-24 22:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api', '0008_alter_wallet_disabled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRecord',
            fields=[
                ('reference_id', models.CharField(max_length=36, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator])),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_api.customer')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_api.wallet')),
            ],
        ),
    ]
