# Generated by Django 4.1 on 2022-08-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api', '0009_balancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancerecord',
            name='status',
            field=models.CharField(default='Failed', max_length=20),
        ),
    ]
